<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIZx2Kwe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIZx2Kwe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIZx2Kwe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIZx2Kwe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIZx2Kwe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IZx2Kwe',
    'container.build_id' => '7b66c3bf',
    'container.build_time' => 1549874657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIZx2Kwe');
